DELETE http://localhost:7712/delete/1
Accept: application/json

###

###
POST http://localhost:7712/admin/add/
Content-Type: application/json

{ "name": "Ulan",
  "address": "Isa156",
  "email": "ulan@gmail.com"
}


###
PUT http://localhost:7712/edit/
Content-Type: application/json

{ "id": 24,
  "name": "uu",
  "address": "111sss",
  "email": "sdsd@gmail.com"
}

###